ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0+aEfYuzc58n32hMoXdcBu2VcCkoKl3vc2CQy4PmWygG1DFNdODRh8//H9Rizu14vfUKkv+oo+td9wIKiQZFQpm8TUQB5V4Et3/8YNsrb06CSPEyMw2xKOW+7szWJu0yoeQQpvX4hgiE4y2pYhxFkVkmAH8IXHlvUSGCov46zpyMb0/5RZzll8So87PEOVUM74v2aWhBQsdlskanRPIp6DLs88OxHbVn81QZ7GfNJqQ7zzbNHZuZ1/zXtojB0CyH4Qs/fH5lmS37T5N9h92D2k8EewEY/0hxRDtq/6LQ56JZqL+IWN0muMIMaFhDWDieMMvvd119k7dTNE0LrTNFz jwalker@zion

write_files:
  - path: /etc/ssh/sshd_config
    content: |
      AllowTcpForwarding      no
      GatewayPorts            no
      PasswordAuthentication  yes # necessary for access from packer build
      X11Forwarding           no
      PermitRootLogin         no
      LoginGraceTime          30s
      MaxAuthTries            5

      Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
      MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com
      KexAlgorithms curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256
      Subsystem   sftp    internal-sftp

k3os:
  password: YourSSHPassword 
  datasource: cdrom
